FROM heasoft:v6.31.1

#RUN mkdir -p /usr/src/astro/spec_analysis/tools
#RUN mkdir -p /usr/src/astro/spec_analysis/data

#WORKDIR /usr/src/astro/spec_analysis/tools

#COPY /data/A1763_img5_exp.fits .
#COPY /data/A1763_bg5_exp.fits .
#COPY ./tools .
#COPY ./data .
COPY requirements.txt .
COPY ciaoinstallrc .
COPY scripts scripts
COPY wrapper.sh .
RUN sudo apt-get update && sudo apt-get install -y python3-pip curl
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN curl -sfL https://cxc.harvard.edu/cgi-gen/ciao/ciao415_install.cgi?standard=true > ciao_install && chmod +x ciao_install
RUN CIAOINSTALLRC=/ciaoinstallrc ./ciao_install
CMD ./wrapper.sh
#CMD ["bash", "/data_prep/data_prep.sh"]
#CMD ["python", "./v2fits.py"]
#CMD ["bash", "specextract"]
#CMD ["bash", "spec.sh"]
#CMD ["bash", "xspec" "- A1763.xcm"]


##Docker is not using my changes when updating my cwd path why? Causing the fits file not to be found
##Needed to make "out" a directory instead of having it be generated by python in docker, why?
##Get data_prep scripts off old macbook, upload to github
